# Generated by Django 4.1.7 on 2023-02-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='fecha_inicio',
            field=models.DateField(auto_now=True),
        ),
    ]
