# Generated by Django 4.1.7 on 2023-02-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_tareas_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='color',
            field=models.CharField(choices=[('primary', 'Azul'), ('secondary', 'Gris'), ('success', 'Verde'), ('danger', 'Rojo'), ('warning', 'Amarillo'), ('info', 'Azul claro'), ('light', 'Blanco'), ('dark', 'Negro')], default='primary', max_length=20),
        ),
    ]
